### ISSUE TITLE
Counter break after I steal or get stolen

### ISSUE THREAD

**Issue by C1sW0uth** [Lolligerhans/cocaco#2]
Hi, love the extension that you're building, I'm using version 3.4.6 and I keep bumping into this issue

Cocaco seems to be broken and stop reading the game log when there are message like "Player 1 steal 1 wheat from You" or "You steal 1 whear from player2". Cocaco didn't register this info since it don't know who "you" is. It skips this line in the gamelog and eventually lead to error, break and stop counting.

Can we add an input box when the user can define for cocaco who he is when this happen?

**Comment by C1sW0uth** [comment]
The following image shows that the stealing message is not parsed by the counter:
![image](https://github.com/user-attachments/assets/f33ed4d8-0194-407b-aaf0-a28af1e08f2d)

**Comment by Lolligerhans** [comment]
Thank you for reporting this issue.

This is not supposed to happen.

I cannot reproduce the behaviour on `v3.4.6`, so I do not know what to change to make it work. Try the following:

- Make sure your name does not have whitespace (` `).
- (opponent names with whitespace may be problematic too) 
- Set [`fixedPlayerName`](https://github.com/Lolligerhans/cocaco/blob/098943f8af3c9fb03e1f8cde97f9c27e4b44d0cb/javascript/explorer.js#L33) to `true` in the file `explorer.js` and enter your username below that line.
- Open the console output. It confirms what it thinks your name is, somewhere at the top, with `You are: <name>`.

Otherwise debugging on your setup would be needed.

**Comment by Lolligerhans** [comment]
Also try [v4.0.1](https://github.com/Lolligerhans/cocaco/releases/tag/v4.0.1). I disabled the new parts, but it has minor tweaks that could affect this.

**Comment by C1sW0uth** [comment]
Perfect, turns out I have to set my own name ([fixedPlayerName]) in the javascript for it to work, may I suggest you include this in the instruction of the project for people who might have the same problem? Or include an interface for player to input their name?

This project is absolutely amazing and it has helped me a ton with my game, thank you!

**Comment by Lolligerhans** [comment]
I think having this issue will suffice until the cause is clear.
